PROXY = ""
EUDIC_TOKEN = ""
EUDIC_ID = "0"
DECK_NAME = "anki_packager"

[[MODEL_PARAM]]
model = "gemini/gemini-2.5-flash" 
api_key = "GEMINI_API_KEY"
rpm = 10 # 每分钟请求次数

# [[MODEL_PARAM]]
# model = "openai/GLM-4-Flash"
# api_key = ""
# api_base = "https://open.bigmodel.cn/api/paas/v4/"
# rpm = 200